### ISSUE TITLE
Incorrect order using filter

### ISSUE THREAD

**Issue by GeoDodo** [omniscale/magnacarto#43]
If you create a config with a filter and you overwrites the PolygonSymbolizer, the order for LineSymbolizer and PolygonSymbolizer is incorrect. As a result you will get polygons with the wrong line stroke.

Example MSS-Config:

```css
#buildings[zoom>=16] {
  polygon-fill: #cccccc;
  line-color: #ff0000;
  line-width: 5;
  [type="commercial"] {
    polygon-fill: #ffff00;
  }
}
```

Output for Mapnik:

``` xml
<Map srs="+init=epsg:3857">
  <Parameters></Parameters>
  <Style name="buildings" filter-mode="first">
    <Rule>
      <!--Zoom{>=16}-->
      <MaxScaleDenominator>12500</MaxScaleDenominator>
      <Filter>([type] = &#39;commercial&#39;)</Filter>
      <LineSymbolizer stroke="#ff0000" stroke-width="0.4"></LineSymbolizer>
      <PolygonSymbolizer fill="#ffff00"></PolygonSymbolizer>
    </Rule>
    <Rule>
      <!--Zoom{>=16}-->
      <MaxScaleDenominator>12500</MaxScaleDenominator>
      <PolygonSymbolizer fill="#cccccc"></PolygonSymbolizer>
      <LineSymbolizer stroke="#ff0000" stroke-width="0.4"></LineSymbolizer>
    </Rule>
  </Style>
  <Layer name="buildings" srs="" status="off" maxzoom="12500">
    <StyleName>buildings</StyleName>
  </Layer>
</Map>
```
